# Generated by Django 3.2.5 on 2022-07-06 18:29

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220706_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmedicine',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Medicine', 'verbose_name_plural': 'historical Medicines'},
        ),
        migrations.AlterModelOptions(
            name='historicalstock',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Stock', 'verbose_name_plural': 'historical Stocks'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'Medicine', 'verbose_name_plural': 'Medicines'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
    ]
