# Generated by Django 3.2.5 on 2022-07-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220706_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmaterial',
            name='uom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='uom',
            field=models.CharField(max_length=50),
        ),
    ]
