# Generated by Django 3.2.5 on 2022-07-27 19:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalFiles',
            new_name='HistoricalPromotionFiles',
        ),
        migrations.RenameModel(
            old_name='Files',
            new_name='PromotionFiles',
        ),
        migrations.AlterModelOptions(
            name='historicalpromotion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Promotion', 'verbose_name_plural': 'historical Promotions'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
    ]
