# Generated by Django 3.2.5 on 2022-07-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220703_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='gender',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='ssn',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='NSS'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='university_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Matricula'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='user',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='user',
            name='ssn',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='NSS'),
        ),
        migrations.AddField(
            model_name='user',
            name='university_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Matricula'),
        ),
    ]
