# Generated by Django 3.2.5 on 2022-07-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220721_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=40, null=True, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=40, null=True, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono'),
        ),
    ]
